### ISSUE TITLE
How to not run tests on release?

### ISSUE THREAD

**Issue by ChameleonTartu** [elgohr/Github-Release-Action#14]
Hi,

I am using Maven, and I have the same setup as you. How can I publish without running tests?

The issue with Maven, as I do `mvn package`, I do testing, even if I exclude tests from there, why would I want to make "double-run" of tests?

How can I exclude run from test GitHub Actions when publishing release?

Thank you in advance!

**Comment by elgohr** [comment]
Hey,
sorry, I don't get it.
This action can be used to create a Github Release (independent of any Maven or testing).
Could you please make an example (actions.yml)?

**Comment by ChameleonTartu** [comment]
@elgohr  Yes, sorry. I see I wasn't clear of what I meant.

You have 2 pipelines:
- test.yml
- publish_release.yml

My question was, how to make run only `publish_release` run when making a release.

My concern is that I don't want both of them to run `test` and `publish_release` but only `publish_release`.

Does it make sense?

**Comment by elgohr** [comment]
I don’t really get the connection to this action.
I guess you could have a look on https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds for orchestrating steps and jobs order/execution
