### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by oleg-alexandrov** [elgohr/Github-Release-Action#42]
This repository does not explain clearly what it does, and what the effect would be. For example, it should say that after it is triggered, a certain release will appear with a certain link. It also does not say if this release packages dependencies or not.

**Comment by elgohr** [comment]
Open for contributions 🙂

**Comment by oleg-alexandrov** [comment]
I tried. See https://github.com/elgohr/Github-Release-Action/pull/43.

I will close this. The discussion can continue on that pull request page.
