### ISSUE TITLE
Choose file path

### ISSUE THREAD

**Issue by yceballost** [elgohr/Github-Release-Action#46]
Hi, 

thanks for this actions!

Is it possible to choose the path of the files that will be included in release pack? To avoid pack the entire repo

Thanks!

**Comment by elgohr** [comment]
Hi, in the a Release in GitHub is a Git tag. What do you see as "packing"? To my knowledge there's nothing like partial tags

**Comment by yceballost** [comment]
I found this workaround and works perfectly

https://feeding.cloud.geek.nz/posts/excluding-files-from-git-archive/
