### ISSUE TITLE
This action doesn't work

### ISSUE THREAD

**Issue by Bouh** [elgohr/Github-Release-Action#6]
This action doesn't work, or documentation are very bad.
I follow the example, and my log show me errors about token.

```
Current runner version: '2.163.1'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'actions/setup-node@v1'
Download action repository 'elgohr/Github-Release-Action@3.0'
##[error](Line: 8, Col: 17):
##[error](Line: 13, Col: 8):
##[error](Line: 8, Col: 17): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN
##[error](Line: 13, Col: 8): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.release
##[error]Fail to load /home/runner/work/_actions/elgohr/Github-Release-Action/3.0/action.yml
```

[Don't waste hours like me on this action use this one which works very well.](https://github.com/actions/create-release)

**Comment by elgohr** [comment]
Sorry, I don't help people that don't know how to behave oneself.

**Comment by elgohr** [comment]
By the way, it's working (as you can see here https://github.com/elgohr/Github-Release-Action/blob/master/.github/workflows/publish_release.yml).
