### ISSUE TITLE
extend action to include prerelease

### ISSUE THREAD

**Issue by bwhitehead0** [elgohr/Github-Release-Action#63]
thoughts on extending the action to support? to include:

- prerelease releases (priority)
- additional release notes (might make sense)

could modify action.yaml to include under inputs:

```yaml
  prerelease:
    description: "Is this a prerelease?"
    required: false
    default: "false"
```
and then update `entrypoint.sh` to read:

```shell
if [ -z "${INPUT_PRERELEASE}" ]; then
    gh release create $INPUT_TAG -t "${INPUT_TITLE}" --generate-notes
else
    gh release create $INPUT_TAG -t "${INPUT_TITLE}" --generate-notes --prerelease
fi
```

the way i'm using this workflow is in a `generate_tagged_release` workflow via `workflow_dispatch`, where our workflow enforces guidelines on versioning, tagging, and releases, and then kicks off subsequent build actions.

in this case, we could have both the release marked GA or prerelease, the user supplies the desired release tag matching our constraints (eg `v1.2.1` or `v1.2.1-RC` for prerelease), which then creates the tag and release, ensuring conformity, and then kicks of subsequent build and other CI and CD processes, generating prerelease or GA artifacts and so on.

adding additional notes input might make sense for teams including additional info, links to release documentation, etc, which may not be available just from commit history etc.

**Comment by elgohr** [comment]
Let me think about it

**Comment by elgohr** [comment]
There you go
https://github.com/elgohr/Github-Release-Action?tab=readme-ov-file#prerelease
